name: Backend CI

on:
  push:
    branches: [main, 'develop**']
    paths:
      - 'backend/**'
  pull_request:
    branches: [main, 'develop**']
    paths:
      - 'backend/**'

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build_java_services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ApiGateWay, ModelService, NotificationService, UserService]
    container:
      image: maven:3.9.6-eclipse-temurin-17
    defaults:
      run:
        working-directory: backend/${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - name: Build & Test ${{ matrix.service }}
        run: mvn clean install

  build_python_service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/ModelApiService
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest