name: Godot Web Export and Deploy to Vercel

on:
  push:
    branches: [main, 'develop', 'develop-*', 'develop/**']
    paths:
      - 'frontend/**'
      - '.github'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir -p frontend/build/web

      - name: Export HTML5 build using Godot
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/frontend":/game \
            -w /game \
            barichello/godot-ci:4.4.1 \
            godot --headless --export-release "Web" build/web/index.html

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm --cwd frontend/build/web