name: Godot Web Export, Dockerize, and Deploy to VPS

on:
  push:
    branches: [main, 'develop', 'develop-*', 'develop/**']
    paths:
      - 'frontend/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir -p frontend/build/web

      - name: Export HTML5 build using Godot
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/frontend":/game \
            -w /game \
            barichello/godot-ci:4.4.1 \
            godot --headless --export-release "Web" build/web/index.html

      - name: Create Dockerfile for NGINX
        run: |
          cat <<EOF > frontend/Dockerfile
          FROM nginx:alpine
          COPY build/web /usr/share/nginx/html
          EOF

      - name: Build Docker image
        run: |
          docker build -t godot-web-app ./frontend

      - name: Save Docker image to tar
        run: |
          mkdir -p /tmp/docker-export  # Убедимся, что директория существует
          docker save godot-web-app -o /tmp/docker-export/godot-web-app.tar

      - name: List files in /tmp/docker-export
        run: ls -lh /tmp/docker-export  # Список файлов для проверки

      - name: Upload image to VPS over SSH
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_PASS: ${{ secrets.PASSWORD }}
          VPS_HOST: ${{ secrets.HOST }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Копируем файл
          sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no /tmp/docker-export/godot-web-app.tar $SSH_USER@$VPS_HOST:/tmp/

          # Загружаем образ и перезапускаем контейнер
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$VPS_HOST <<EOF
            docker load -i /tmp/godot-web-app.tar
            docker stop godot-web || true && docker rm godot-web || true
            docker run -d --name godot-web -p 80:80 godot-web-app
          EOF
