name: Godot Web and Android Export
on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create export directory
        run: mkdir -p frontend/build/web

      - name: Export HTML5 build using Godot
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/frontend":/game \
            -w /game \
            barichello/godot-ci:4.4.1 \
            godot --headless --export-release "Web" build/web/index.html

      - name: Upload web artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build/web

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Android export directory
        run: mkdir -p frontend/build/android

      - name: Export Android Debug APK using Godot
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/frontend":/game \
            -w /game \
            barichello/godot-ci:4.4.1 \
            godot --headless --verbose --export-debug "Android" build/android/game-debug.apk

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name:  defense-and-discover
          path: frontend/build/android/game-debug.apk

  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4